// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for About Page documents */
interface AboutPageDocumentData {
  /**
   * Title field in *About Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<AboutPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *About Page → Slice Zone*
 *
 */
type AboutPageDocumentDataSlicesSlice =
  | CustomInnovationSlice
  | TheTeamSlice
  | InvestorsSlice;
/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;
/** Content for Home Page documents */
interface HomePageDocumentData {
  /**
   * Title field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice =
  | HeroSlice
  | BluePrintSlice
  | ProductShowcaseSlice
  | OurSupportSlice
  | HeroAboutSlice
  | BandicootImageSequenceSlice;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;
export type AllDocumentTypes = AboutPageDocument | HomePageDocument;
/**
 * Primary content in BandicootImageSequence → Primary
 *
 */
interface BandicootImageSequenceSliceDefaultPrimary {
  /**
   * Title field in *BandicootImageSequence → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bandicoot_image_sequence.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
}
/**
 * Default variation for BandicootImageSequence Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BandicootImageSequenceSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<BandicootImageSequenceSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *BandicootImageSequence*
 *
 */
type BandicootImageSequenceSliceVariation = BandicootImageSequenceSliceDefault;
/**
 * BandicootImageSequence Shared Slice
 *
 * - **API ID**: `bandicoot_image_sequence`
 * - **Description**: `BandicootImageSequence`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BandicootImageSequenceSlice = prismicT.SharedSlice<
  "bandicoot_image_sequence",
  BandicootImageSequenceSliceVariation
>;
/**
 * Primary content in FeatureCarousel → Primary
 *
 */
interface BluePrintSliceDefaultPrimary {
  /**
   * Title field in *FeatureCarousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blue_print.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
}
/**
 * Item in FeatureCarousel → Items
 *
 */
export interface BluePrintSliceDefaultItem {
  /**
   * Eyebrow text field in *FeatureCarousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blue_print.items[].eyebrow_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  eyebrow_text: prismicT.RichTextField;
  /**
   * Blue Print Id field in *FeatureCarousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blue_print.items[].blue_print_id
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  blue_print_id: prismicT.RichTextField;
  /**
   * Blue Print Title field in *FeatureCarousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blue_print.items[].blue_print_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  blue_print_title: prismicT.RichTextField;
  /**
   * Blue Print Description field in *FeatureCarousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blue_print.items[].blue_print_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  blue_print_description: prismicT.RichTextField;
  /**
   * Blue Print Asset field in *FeatureCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blue_print.items[].blue_print_asset
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  blue_print_asset: prismicT.ImageField<never>;
}
/**
 * Default variation for FeatureCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BluePrintSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<BluePrintSliceDefaultPrimary>,
  Simplify<BluePrintSliceDefaultItem>
>;
/**
 * Slice variation for *FeatureCarousel*
 *
 */
type BluePrintSliceVariation = BluePrintSliceDefault;
/**
 * FeatureCarousel Shared Slice
 *
 * - **API ID**: `blue_print`
 * - **Description**: `BluePrint`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BluePrintSlice = prismicT.SharedSlice<
  "blue_print",
  BluePrintSliceVariation
>;
/**
 * Default variation for CustomInnovation Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CustomInnovationSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;
/**
 * Slice variation for *CustomInnovation*
 *
 */
type CustomInnovationSliceVariation = CustomInnovationSliceDefault;
/**
 * CustomInnovation Shared Slice
 *
 * - **API ID**: `custom_innovation`
 * - **Description**: `CustomInnovation`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CustomInnovationSlice = prismicT.SharedSlice<
  "custom_innovation",
  CustomInnovationSliceVariation
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Hero Video field in *Hero → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_video
   * - **Documentation**: https://prismic.io/docs/core-concepts/embed
   *
   */
  hero_video: prismicT.EmbedField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in HeroAbout → Primary
 *
 */
interface HeroAboutSliceDefaultPrimary {
  /**
   * Title field in *HeroAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Description field in *HeroAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Stats A field in *HeroAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.primary.stats_a
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  stats_a: prismicT.RichTextField;
  /**
   * Stats A Description field in *HeroAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.primary.stats_a_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  stats_a_description: prismicT.RichTextField;
  /**
   * Stats B field in *HeroAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.primary.stats_b
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  stats_b: prismicT.RichTextField;
  /**
   * Stats B Description field in *HeroAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.primary.stats_b_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  stats_b_description: prismicT.RichTextField;
}
/**
 * Item in HeroAbout → Items
 *
 */
export interface HeroAboutSliceDefaultItem {
  /**
   * Stats field in *HeroAbout → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.items[].stats
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  stats: prismicT.RichTextField;
  /**
   * Stats Description field in *HeroAbout → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_about.items[].stats_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  stats_description: prismicT.RichTextField;
}
/**
 * Default variation for HeroAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroAboutSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HeroAboutSliceDefaultPrimary>,
  Simplify<HeroAboutSliceDefaultItem>
>;
/**
 * Slice variation for *HeroAbout*
 *
 */
type HeroAboutSliceVariation = HeroAboutSliceDefault;
/**
 * HeroAbout Shared Slice
 *
 * - **API ID**: `hero_about`
 * - **Description**: `HeroAbout`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroAboutSlice = prismicT.SharedSlice<
  "hero_about",
  HeroAboutSliceVariation
>;
/**
 * Primary content in Investors → Primary
 *
 */
interface InvestorsSliceDefaultPrimary {
  /**
   * Title field in *Investors → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investors.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * SubTitle field in *Investors → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investors.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  subtitle: prismicT.RichTextField;
}
/**
 * Item in Investors → Items
 *
 */
export interface InvestorsSliceDefaultItem {
  /**
   * Image field in *Investors → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: investors.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * Name field in *Investors → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investors.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismicT.RichTextField;
  /**
   * Role field in *Investors → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investors.items[].role
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  role: prismicT.RichTextField;
  /**
   * Company Name field in *Investors → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investors.items[].company_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  company_name: prismicT.RichTextField;
}
/**
 * Default variation for Investors Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InvestorsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<InvestorsSliceDefaultPrimary>,
  Simplify<InvestorsSliceDefaultItem>
>;
/**
 * Slice variation for *Investors*
 *
 */
type InvestorsSliceVariation = InvestorsSliceDefault;
/**
 * Investors Shared Slice
 *
 * - **API ID**: `investors`
 * - **Description**: `Investors`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InvestorsSlice = prismicT.SharedSlice<
  "investors",
  InvestorsSliceVariation
>;
/**
 * Primary content in OurSupport → Primary
 *
 */
interface OurSupportSliceDefaultPrimary {
  /**
   * Title field in *OurSupport → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Description field in *OurSupport → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * News Date field in *OurSupport → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.primary.news_date
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  news_date: prismicT.RichTextField;
  /**
   * News Title field in *OurSupport → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.primary.news_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  news_title: prismicT.RichTextField;
  /**
   * News Description field in *OurSupport → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.primary.news_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  news_description: prismicT.RichTextField;
}
/**
 * Item in OurSupport → Items
 *
 */
export interface OurSupportSliceDefaultItem {
  /**
   * Logo field in *OurSupport → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.items[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
  /**
   * Image field in *OurSupport → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_support.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Default variation for OurSupport Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OurSupportSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<OurSupportSliceDefaultPrimary>,
  Simplify<OurSupportSliceDefaultItem>
>;
/**
 * Slice variation for *OurSupport*
 *
 */
type OurSupportSliceVariation = OurSupportSliceDefault;
/**
 * OurSupport Shared Slice
 *
 * - **API ID**: `our_support`
 * - **Description**: `OurSupport`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OurSupportSlice = prismicT.SharedSlice<
  "our_support",
  OurSupportSliceVariation
>;
/**
 * Primary content in ProductShowcase → Primary
 *
 */
interface ProductShowcaseSliceDefaultPrimary {
  /**
   * Title field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Description field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Item in ProductShowcase → Items
 *
 */
export interface ProductShowcaseSliceDefaultItem {
  /**
   * Product Image field in *ProductShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].product_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  product_image: prismicT.ImageField<never>;
  /**
   * Product Title field in *ProductShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].product_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  product_title: prismicT.RichTextField;
  /**
   * Product Description field in *ProductShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_showcase.items[].product_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  product_description: prismicT.RichTextField;
}
/**
 * Default variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductShowcaseSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ProductShowcaseSliceDefaultPrimary>,
  Simplify<ProductShowcaseSliceDefaultItem>
>;
/**
 * Slice variation for *ProductShowcase*
 *
 */
type ProductShowcaseSliceVariation = ProductShowcaseSliceDefault;
/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `product_showcase`
 * - **Description**: `ProductShowcase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductShowcaseSlice = prismicT.SharedSlice<
  "product_showcase",
  ProductShowcaseSliceVariation
>;
/**
 * Primary content in TheTeam → Primary
 *
 */
interface TheTeamSliceDefaultPrimary {
  /**
   * Title field in *TheTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_team.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * SubTitle field in *TheTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_team.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  subtitle: prismicT.RichTextField;
}
/**
 * Item in TheTeam → Items
 *
 */
export interface TheTeamSliceDefaultItem {
  /**
   * Image field in *TheTeam → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_team.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * Full Name field in *TheTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_team.items[].full_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  full_name: prismicT.RichTextField;
  /**
   * Position field in *TheTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: the_team.items[].position
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  position: prismicT.RichTextField;
}
/**
 * Default variation for TheTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TheTeamSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TheTeamSliceDefaultPrimary>,
  Simplify<TheTeamSliceDefaultItem>
>;
/**
 * Slice variation for *TheTeam*
 *
 */
type TheTeamSliceVariation = TheTeamSliceDefault;
/**
 * TheTeam Shared Slice
 *
 * - **API ID**: `the_team`
 * - **Description**: `TheTeam`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TheTeamSlice = prismicT.SharedSlice<
  "the_team",
  TheTeamSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      AboutPageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      HomePageDocument,
      AllDocumentTypes,
      BandicootImageSequenceSliceDefaultPrimary,
      BandicootImageSequenceSliceDefault,
      BandicootImageSequenceSliceVariation,
      BandicootImageSequenceSlice,
      BluePrintSliceDefaultPrimary,
      BluePrintSliceDefaultItem,
      BluePrintSliceDefault,
      BluePrintSliceVariation,
      BluePrintSlice,
      CustomInnovationSliceDefault,
      CustomInnovationSliceVariation,
      CustomInnovationSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
      HeroSlice,
      HeroAboutSliceDefaultPrimary,
      HeroAboutSliceDefaultItem,
      HeroAboutSliceDefault,
      HeroAboutSliceVariation,
      HeroAboutSlice,
      InvestorsSliceDefaultPrimary,
      InvestorsSliceDefaultItem,
      InvestorsSliceDefault,
      InvestorsSliceVariation,
      InvestorsSlice,
      OurSupportSliceDefaultPrimary,
      OurSupportSliceDefaultItem,
      OurSupportSliceDefault,
      OurSupportSliceVariation,
      OurSupportSlice,
      ProductShowcaseSliceDefaultPrimary,
      ProductShowcaseSliceDefaultItem,
      ProductShowcaseSliceDefault,
      ProductShowcaseSliceVariation,
      ProductShowcaseSlice,
      TheTeamSliceDefaultPrimary,
      TheTeamSliceDefaultItem,
      TheTeamSliceDefault,
      TheTeamSliceVariation,
      TheTeamSlice,
    };
  }
}
