// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_vision_mission: dynamic(() => import("./AboutVisionMission")),
  bandicoot_image_sequence: dynamic(() => import("./BandicootImageSequence")),
  blue_print: dynamic(() => import("./FeatureCarousel")),
  career_benefits: dynamic(() => import("./CareerBenefits")),
  career_child_hero: dynamic(() => import("./CareerChildHero")),
  career_child_information: dynamic(() => import("./CareerChildInformation")),
  career_hero: dynamic(() => import("./CareerHero")),
  career_mission: dynamic(() => import("./CareerMission")),
  career_open_position: dynamic(() => import("./CareerOpenPosition")),
  custom_innovation: dynamic(() => import("./CustomInnovation")),
  hero: dynamic(() => import("./Hero")),
  hero_about: dynamic(() => import("./HeroAbout")),
  investors: dynamic(() => import("./Investors")),
  news_room: dynamic(() => import("./NewsRoom")),
  our_support: dynamic(() => import("./OurSupport")),
  product_showcase: dynamic(() => import("./ProductShowcase")),
  the_team: dynamic(() => import("./TheTeam")),
};
